### ISSUE TITLE
Custom email

### ISSUE THREAD

**Issue by Krato** [in-the-beam/laravel-email-confirmation#1]
Hi,

First thanks for this package.

But how can I add a custom email without change the core?

Thanks!

**Comment by h-zone** [comment]
do not quite understand. can be more?

**Comment by Krato** [comment]
Sure. Imagine that I want to send a custom email instead the email you prepared. Or instead Laravel default email views.

Do you understand?

**Comment by h-zone** [comment]
But why then 
```php artisan vendor:publish --tag=laravel-notifications```
and/or
```php artisan vendor:publish --tag=laravel-mail```
???
At last You can edit emails as You wish.
:-)

**Comment by Krato** [comment]
Sure, I can modify this.

But, if for example I want to remove `message3` from the email to confirm email?

Would be great to be able to choose a Notification class from an option in the config file.

Do you understand me now? 😄
